"""Update relationships and add foreign keys

Revision ID: 14757c390e9b
Revises: 11d434165206
Create Date: 2024-05-18 22:34:11.994104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14757c390e9b'
down_revision: Union[str, None] = '11d434165206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags_pictures', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tags_pictures', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tags_pictures_picture_id_fkey', 'tags_pictures', type_='foreignkey')
    op.drop_constraint('tags_pictures_tag_id_fkey', 'tags_pictures', type_='foreignkey')
    op.create_foreign_key(None, 'tags_pictures', 'pictures', ['picture_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_pictures', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_pictures', type_='foreignkey')
    op.drop_constraint(None, 'tags_pictures', type_='foreignkey')
    op.create_foreign_key('tags_pictures_tag_id_fkey', 'tags_pictures', 'users', ['tag_id'], ['id'])
    op.create_foreign_key('tags_pictures_picture_id_fkey', 'tags_pictures', 'pictures', ['picture_id'], ['id'])
    op.alter_column('tags_pictures', 'tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tags_pictures', 'picture_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
