"""Fix schema discrepancies

Revision ID: 1c9e693ec98d
Revises: e537790ef1c3
Create Date: 2024-05-23 16:00:14.946476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9e693ec98d'
down_revision: Union[str, None] = 'e537790ef1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('pictures', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'moderator', 'user', name='role'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('pictures', 'updated_at')
    op.drop_column('pictures', 'created_at')
    # ### end Alembic commands ###
