"""Photos

Revision ID: 48c9b4d0a799
Revises: ad090f5ad058
Create Date: 2024-05-20 22:30:27.765410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c9b4d0a799'
down_revision: Union[str, None] = 'ad090f5ad058'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'text',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('pictures', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('pictures', 'qr_code_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('pictures', 'image_url',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_pictures_id'), 'pictures', ['id'], unique=False)
    op.create_index(op.f('ix_pictures_image_url'), 'pictures', ['image_url'], unique=True)
    op.create_unique_constraint(None, 'tags', ['name'])
    op.drop_constraint('tags_pictures_picture_id_fkey', 'tags_pictures', type_='foreignkey')
    op.drop_constraint('tags_pictures_tag_id_fkey', 'tags_pictures', type_='foreignkey')
    op.create_foreign_key(None, 'tags_pictures', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tags_pictures', 'pictures', ['picture_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags_pictures', type_='foreignkey')
    op.drop_constraint(None, 'tags_pictures', type_='foreignkey')
    op.create_foreign_key('tags_pictures_tag_id_fkey', 'tags_pictures', 'users', ['tag_id'], ['id'])
    op.create_foreign_key('tags_pictures_picture_id_fkey', 'tags_pictures', 'pictures', ['picture_id'], ['id'])
    op.drop_constraint(None, 'tags', type_='unique')
    op.drop_index(op.f('ix_pictures_image_url'), table_name='pictures')
    op.drop_index(op.f('ix_pictures_id'), table_name='pictures')
    op.alter_column('pictures', 'image_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('pictures', 'qr_code_url',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('pictures', 'description')
    op.alter_column('comments', 'text',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
